# Site Settings
logo: /media/bio.png
title: BioShack
description: Building the Future with Open Science

url: "https://megdna.github.io"
baseurl: "/bio"
permalink: :title

code: https://github.com/bioshack
donate: https://ko-fi.com/bioshack
social: 

email: bio@d8a.org
goatcounter: bio

nav:
  - name: About
    link: /about
  - name: Contact
    link: /contact
  - name: Posts
    link: /posts
  
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "media/**"
    values:
      sitemap: false